server:
  http_port: ${SERVER_HTTP_PORT}
  grpc_port: ${SERVER_GRPC_PORT}

central_backend:
  host: ${CENTRAL_BACKEND_HOST}
  http_port: ${CENTRAL_BACKEND_HTTP_PORT}
  grpc_port: ${CENTRAL_BACKEND_GRPC_PORT}
  allow_failure: ${ALLOW_CENTRAL_BACKEND_FAILURE}

sensor:
  i2c_device: ${SENSOR_I2C_DEVICE}
  i2c_address: ${SENSOR_I2C_ADDRESS}
