#개발용
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - --path.rootfs=/host
      - --web.listen-address=:${NODE_EXPORTER_HTTP_PORT:-9100}
    restart: unless-stopped
    ports:
      - "${NODE_EXPORTER_HTTP_PORT:-9100}:${NODE_EXPORTER_HTTP_PORT:-9100}"
    volumes:
      - /:/host:ro
