services:
  server:
    platform: ${DOCKER_PLATFORM:-linux/arm64}
    image: eco-knock-be-embedded:arm64
    restart: unless-stopped
    user: "0:0"
    env_file:
      - .env
    devices:
      - /dev/i2c-1:/dev/i2c-1
    volumes:
      - ./data:/app/data
    ports:
      - "${SERVER_HTTP_PORT}:${SERVER_HTTP_PORT}"

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - --path.rootfs=/host
      - --web.listen-address=:${NODE_EXPORTER_HTTP_PORT:-9100}
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro
