// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/sensor/v1/sensor.proto

package sensorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportSensorRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	TemperatureC     float64                `protobuf:"fixed64,2,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	HumidityRh       float64                `protobuf:"fixed64,3,opt,name=humidity_rh,json=humidityRh,proto3" json:"humidity_rh,omitempty"`
	GasResistanceOhm float64                `protobuf:"fixed64,4,opt,name=gas_resistance_ohm,json=gasResistanceOhm,proto3" json:"gas_resistance_ohm,omitempty"`
	MeasuredAtUnixMs int64                  `protobuf:"varint,5,opt,name=measured_at_unix_ms,json=measuredAtUnixMs,proto3" json:"measured_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportSensorRequest) Reset() {
	*x = ReportSensorRequest{}
	mi := &file_proto_sensor_v1_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSensorRequest) ProtoMessage() {}

func (x *ReportSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sensor_v1_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSensorRequest.ProtoReflect.Descriptor instead.
func (*ReportSensorRequest) Descriptor() ([]byte, []int) {
	return file_proto_sensor_v1_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *ReportSensorRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ReportSensorRequest) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *ReportSensorRequest) GetHumidityRh() float64 {
	if x != nil {
		return x.HumidityRh
	}
	return 0
}

func (x *ReportSensorRequest) GetGasResistanceOhm() float64 {
	if x != nil {
		return x.GasResistanceOhm
	}
	return 0
}

func (x *ReportSensorRequest) GetMeasuredAtUnixMs() int64 {
	if x != nil {
		return x.MeasuredAtUnixMs
	}
	return 0
}

type ReportSensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSensorResponse) Reset() {
	*x = ReportSensorResponse{}
	mi := &file_proto_sensor_v1_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSensorResponse) ProtoMessage() {}

func (x *ReportSensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sensor_v1_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSensorResponse.ProtoReflect.Descriptor instead.
func (*ReportSensorResponse) Descriptor() ([]byte, []int) {
	return file_proto_sensor_v1_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *ReportSensorResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_sensor_v1_sensor_proto protoreflect.FileDescriptor

const file_proto_sensor_v1_sensor_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/sensor/v1/sensor.proto\x12\tsensor.v1\"\xd5\x01\n" +
	"\x13ReportSensorRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12#\n" +
	"\rtemperature_c\x18\x02 \x01(\x01R\ftemperatureC\x12\x1f\n" +
	"\vhumidity_rh\x18\x03 \x01(\x01R\n" +
	"humidityRh\x12,\n" +
	"\x12gas_resistance_ohm\x18\x04 \x01(\x01R\x10gasResistanceOhm\x12-\n" +
	"\x13measured_at_unix_ms\x18\x05 \x01(\x03R\x10measuredAtUnixMs\"2\n" +
	"\x14ReportSensorResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2`\n" +
	"\rSensorService\x12O\n" +
	"\fReportSensor\x12\x1e.sensor.v1.ReportSensorRequest\x1a\x1f.sensor.v1.ReportSensorResponseB;Z9eco-knock-be-embedded/internal/grpc/pb/sensor/v1;sensorpbb\x06proto3"

var (
	file_proto_sensor_v1_sensor_proto_rawDescOnce sync.Once
	file_proto_sensor_v1_sensor_proto_rawDescData []byte
)

func file_proto_sensor_v1_sensor_proto_rawDescGZIP() []byte {
	file_proto_sensor_v1_sensor_proto_rawDescOnce.Do(func() {
		file_proto_sensor_v1_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sensor_v1_sensor_proto_rawDesc), len(file_proto_sensor_v1_sensor_proto_rawDesc)))
	})
	return file_proto_sensor_v1_sensor_proto_rawDescData
}

var file_proto_sensor_v1_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sensor_v1_sensor_proto_goTypes = []any{
	(*ReportSensorRequest)(nil),  // 0: sensor.v1.ReportSensorRequest
	(*ReportSensorResponse)(nil), // 1: sensor.v1.ReportSensorResponse
}
var file_proto_sensor_v1_sensor_proto_depIdxs = []int32{
	0, // 0: sensor.v1.SensorService.ReportSensor:input_type -> sensor.v1.ReportSensorRequest
	1, // 1: sensor.v1.SensorService.ReportSensor:output_type -> sensor.v1.ReportSensorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sensor_v1_sensor_proto_init() }
func file_proto_sensor_v1_sensor_proto_init() {
	if File_proto_sensor_v1_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sensor_v1_sensor_proto_rawDesc), len(file_proto_sensor_v1_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sensor_v1_sensor_proto_goTypes,
		DependencyIndexes: file_proto_sensor_v1_sensor_proto_depIdxs,
		MessageInfos:      file_proto_sensor_v1_sensor_proto_msgTypes,
	}.Build()
	File_proto_sensor_v1_sensor_proto = out.File
	file_proto_sensor_v1_sensor_proto_goTypes = nil
	file_proto_sensor_v1_sensor_proto_depIdxs = nil
}
