// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/sensor/v1/sensor.proto

package sensorv1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentSensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentSensorRequest) Reset() {
	*x = GetCurrentSensorRequest{}
	mi := &file_proto_sensor_v1_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSensorRequest) ProtoMessage() {}

func (x *GetCurrentSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sensor_v1_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSensorRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentSensorRequest) Descriptor() ([]byte, []int) {
	return file_proto_sensor_v1_sensor_proto_rawDescGZIP(), []int{0}
}

type GetCurrentSensorResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TemperatureC     float64                `protobuf:"fixed64,1,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	HumidityRh       float64                `protobuf:"fixed64,2,opt,name=humidity_rh,json=humidityRh,proto3" json:"humidity_rh,omitempty"`
	GasResistanceOhm float64                `protobuf:"fixed64,3,opt,name=gas_resistance_ohm,json=gasResistanceOhm,proto3" json:"gas_resistance_ohm,omitempty"`
	Status           uint32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	GasValid         bool                   `protobuf:"varint,5,opt,name=gas_valid,json=gasValid,proto3" json:"gas_valid,omitempty"`
	HeatStable       bool                   `protobuf:"varint,6,opt,name=heat_stable,json=heatStable,proto3" json:"heat_stable,omitempty"`
	MeasuredAtUnixMs int64                  `protobuf:"varint,7,opt,name=measured_at_unix_ms,json=measuredAtUnixMs,proto3" json:"measured_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCurrentSensorResponse) Reset() {
	*x = GetCurrentSensorResponse{}
	mi := &file_proto_sensor_v1_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentSensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentSensorResponse) ProtoMessage() {}

func (x *GetCurrentSensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sensor_v1_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentSensorResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentSensorResponse) Descriptor() ([]byte, []int) {
	return file_proto_sensor_v1_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentSensorResponse) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *GetCurrentSensorResponse) GetHumidityRh() float64 {
	if x != nil {
		return x.HumidityRh
	}
	return 0
}

func (x *GetCurrentSensorResponse) GetGasResistanceOhm() float64 {
	if x != nil {
		return x.GasResistanceOhm
	}
	return 0
}

func (x *GetCurrentSensorResponse) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCurrentSensorResponse) GetGasValid() bool {
	if x != nil {
		return x.GasValid
	}
	return false
}

func (x *GetCurrentSensorResponse) GetHeatStable() bool {
	if x != nil {
		return x.HeatStable
	}
	return false
}

func (x *GetCurrentSensorResponse) GetMeasuredAtUnixMs() int64 {
	if x != nil {
		return x.MeasuredAtUnixMs
	}
	return 0
}

var File_proto_sensor_v1_sensor_proto protoreflect.FileDescriptor

const file_proto_sensor_v1_sensor_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/sensor/v1/sensor.proto\x12\tsensor.v1\"\x19\n" +
	"\x17GetCurrentSensorRequest\"\x93\x02\n" +
	"\x18GetCurrentSensorResponse\x12#\n" +
	"\rtemperature_c\x18\x01 \x01(\x01R\ftemperatureC\x12\x1f\n" +
	"\vhumidity_rh\x18\x02 \x01(\x01R\n" +
	"humidityRh\x12,\n" +
	"\x12gas_resistance_ohm\x18\x03 \x01(\x01R\x10gasResistanceOhm\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\x12\x1b\n" +
	"\tgas_valid\x18\x05 \x01(\bR\bgasValid\x12\x1f\n" +
	"\vheat_stable\x18\x06 \x01(\bR\n" +
	"heatStable\x12-\n" +
	"\x13measured_at_unix_ms\x18\a \x01(\x03R\x10measuredAtUnixMs2l\n" +
	"\rSensorService\x12[\n" +
	"\x10GetCurrentSensor\x12\".sensor.v1.GetCurrentSensorRequest\x1a#.sensor.v1.GetCurrentSensorResponseB=Z;eco-knock-be-embedded/internal/grpc/pb/sensor/v1;sensorv1pbb\x06proto3"

var (
	file_proto_sensor_v1_sensor_proto_rawDescOnce sync.Once
	file_proto_sensor_v1_sensor_proto_rawDescData []byte
)

func file_proto_sensor_v1_sensor_proto_rawDescGZIP() []byte {
	file_proto_sensor_v1_sensor_proto_rawDescOnce.Do(func() {
		file_proto_sensor_v1_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sensor_v1_sensor_proto_rawDesc), len(file_proto_sensor_v1_sensor_proto_rawDesc)))
	})
	return file_proto_sensor_v1_sensor_proto_rawDescData
}

var file_proto_sensor_v1_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sensor_v1_sensor_proto_goTypes = []any{
	(*GetCurrentSensorRequest)(nil),  // 0: sensor.v1.GetCurrentSensorRequest
	(*GetCurrentSensorResponse)(nil), // 1: sensor.v1.GetCurrentSensorResponse
}
var file_proto_sensor_v1_sensor_proto_depIdxs = []int32{
	0, // 0: sensor.v1.SensorService.GetCurrentSensor:input_type -> sensor.v1.GetCurrentSensorRequest
	1, // 1: sensor.v1.SensorService.GetCurrentSensor:output_type -> sensor.v1.GetCurrentSensorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sensor_v1_sensor_proto_init() }
func file_proto_sensor_v1_sensor_proto_init() {
	if File_proto_sensor_v1_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sensor_v1_sensor_proto_rawDesc), len(file_proto_sensor_v1_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sensor_v1_sensor_proto_goTypes,
		DependencyIndexes: file_proto_sensor_v1_sensor_proto_depIdxs,
		MessageInfos:      file_proto_sensor_v1_sensor_proto_msgTypes,
	}.Build()
	File_proto_sensor_v1_sensor_proto = out.File
	file_proto_sensor_v1_sensor_proto_goTypes = nil
	file_proto_sensor_v1_sensor_proto_depIdxs = nil
}
