// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/airpurifier/v1/airpurifier.proto

package airpurifierpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AirPurifierService_GetCurrentAirPurifier_FullMethodName = "/airpurifier.v1.AirPurifierService/GetCurrentAirPurifier"
)

// AirPurifierServiceClient is the client API for AirPurifierService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AirPurifierServiceClient interface {
	GetCurrentAirPurifier(ctx context.Context, in *GetCurrentAirPurifierRequest, opts ...grpc.CallOption) (*GetCurrentAirPurifierResponse, error)
}

type airPurifierServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAirPurifierServiceClient(cc grpc.ClientConnInterface) AirPurifierServiceClient {
	return &airPurifierServiceClient{cc}
}

func (c *airPurifierServiceClient) GetCurrentAirPurifier(ctx context.Context, in *GetCurrentAirPurifierRequest, opts ...grpc.CallOption) (*GetCurrentAirPurifierResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentAirPurifierResponse)
	err := c.cc.Invoke(ctx, AirPurifierService_GetCurrentAirPurifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AirPurifierServiceServer is the server API for AirPurifierService service.
// All implementations must embed UnimplementedAirPurifierServiceServer
// for forward compatibility.
type AirPurifierServiceServer interface {
	GetCurrentAirPurifier(context.Context, *GetCurrentAirPurifierRequest) (*GetCurrentAirPurifierResponse, error)
	mustEmbedUnimplementedAirPurifierServiceServer()
}

// UnimplementedAirPurifierServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAirPurifierServiceServer struct{}

func (UnimplementedAirPurifierServiceServer) GetCurrentAirPurifier(context.Context, *GetCurrentAirPurifierRequest) (*GetCurrentAirPurifierResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentAirPurifier not implemented")
}
func (UnimplementedAirPurifierServiceServer) mustEmbedUnimplementedAirPurifierServiceServer() {}
func (UnimplementedAirPurifierServiceServer) testEmbeddedByValue()                            {}

// UnsafeAirPurifierServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AirPurifierServiceServer will
// result in compilation errors.
type UnsafeAirPurifierServiceServer interface {
	mustEmbedUnimplementedAirPurifierServiceServer()
}

func RegisterAirPurifierServiceServer(s grpc.ServiceRegistrar, srv AirPurifierServiceServer) {
	// If the following call panics, it indicates UnimplementedAirPurifierServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AirPurifierService_ServiceDesc, srv)
}

func _AirPurifierService_GetCurrentAirPurifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentAirPurifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AirPurifierServiceServer).GetCurrentAirPurifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AirPurifierService_GetCurrentAirPurifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AirPurifierServiceServer).GetCurrentAirPurifier(ctx, req.(*GetCurrentAirPurifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AirPurifierService_ServiceDesc is the grpc.ServiceDesc for AirPurifierService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AirPurifierService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "airpurifier.v1.AirPurifierService",
	HandlerType: (*AirPurifierServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentAirPurifier",
			Handler:    _AirPurifierService_GetCurrentAirPurifier_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/airpurifier/v1/airpurifier.proto",
}
