// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/lightsensor/v1/lightsensor.proto

package lightsensorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCurrentLightSensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentLightSensorRequest) Reset() {
	*x = GetCurrentLightSensorRequest{}
	mi := &file_proto_lightsensor_v1_lightsensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLightSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLightSensorRequest) ProtoMessage() {}

func (x *GetCurrentLightSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightsensor_v1_lightsensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLightSensorRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentLightSensorRequest) Descriptor() ([]byte, []int) {
	return file_proto_lightsensor_v1_lightsensor_proto_rawDescGZIP(), []int{0}
}

type GetCurrentLightSensorResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Lux              float64                `protobuf:"fixed64,1,opt,name=lux,proto3" json:"lux,omitempty"`
	RawAls           uint32                 `protobuf:"varint,2,opt,name=raw_als,json=rawAls,proto3" json:"raw_als,omitempty"`
	RawWhite         uint32                 `protobuf:"varint,3,opt,name=raw_white,json=rawWhite,proto3" json:"raw_white,omitempty"`
	MeasuredAtUnixMs int64                  `protobuf:"varint,4,opt,name=measured_at_unix_ms,json=measuredAtUnixMs,proto3" json:"measured_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCurrentLightSensorResponse) Reset() {
	*x = GetCurrentLightSensorResponse{}
	mi := &file_proto_lightsensor_v1_lightsensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentLightSensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentLightSensorResponse) ProtoMessage() {}

func (x *GetCurrentLightSensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lightsensor_v1_lightsensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentLightSensorResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentLightSensorResponse) Descriptor() ([]byte, []int) {
	return file_proto_lightsensor_v1_lightsensor_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentLightSensorResponse) GetLux() float64 {
	if x != nil {
		return x.Lux
	}
	return 0
}

func (x *GetCurrentLightSensorResponse) GetRawAls() uint32 {
	if x != nil {
		return x.RawAls
	}
	return 0
}

func (x *GetCurrentLightSensorResponse) GetRawWhite() uint32 {
	if x != nil {
		return x.RawWhite
	}
	return 0
}

func (x *GetCurrentLightSensorResponse) GetMeasuredAtUnixMs() int64 {
	if x != nil {
		return x.MeasuredAtUnixMs
	}
	return 0
}

var File_proto_lightsensor_v1_lightsensor_proto protoreflect.FileDescriptor

const file_proto_lightsensor_v1_lightsensor_proto_rawDesc = "" +
	"\n" +
	"&proto/lightsensor/v1/lightsensor.proto\x12\x0elightsensor.v1\"\x1e\n" +
	"\x1cGetCurrentLightSensorRequest\"\x96\x01\n" +
	"\x1dGetCurrentLightSensorResponse\x12\x10\n" +
	"\x03lux\x18\x01 \x01(\x01R\x03lux\x12\x17\n" +
	"\araw_als\x18\x02 \x01(\rR\x06rawAls\x12\x1b\n" +
	"\traw_white\x18\x03 \x01(\rR\brawWhite\x12-\n" +
	"\x13measured_at_unix_ms\x18\x04 \x01(\x03R\x10measuredAtUnixMs2\x8a\x01\n" +
	"\x12LightSensorService\x12t\n" +
	"\x15GetCurrentLightSensor\x12,.lightsensor.v1.GetCurrentLightSensorRequest\x1a-.lightsensor.v1.GetCurrentLightSensorResponseBBZ@eco-knock-be-embedded/internal/grpc/pb/lightsensor;lightsensorpbb\x06proto3"

var (
	file_proto_lightsensor_v1_lightsensor_proto_rawDescOnce sync.Once
	file_proto_lightsensor_v1_lightsensor_proto_rawDescData []byte
)

func file_proto_lightsensor_v1_lightsensor_proto_rawDescGZIP() []byte {
	file_proto_lightsensor_v1_lightsensor_proto_rawDescOnce.Do(func() {
		file_proto_lightsensor_v1_lightsensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lightsensor_v1_lightsensor_proto_rawDesc), len(file_proto_lightsensor_v1_lightsensor_proto_rawDesc)))
	})
	return file_proto_lightsensor_v1_lightsensor_proto_rawDescData
}

var file_proto_lightsensor_v1_lightsensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_lightsensor_v1_lightsensor_proto_goTypes = []any{
	(*GetCurrentLightSensorRequest)(nil),  // 0: lightsensor.v1.GetCurrentLightSensorRequest
	(*GetCurrentLightSensorResponse)(nil), // 1: lightsensor.v1.GetCurrentLightSensorResponse
}
var file_proto_lightsensor_v1_lightsensor_proto_depIdxs = []int32{
	0, // 0: lightsensor.v1.LightSensorService.GetCurrentLightSensor:input_type -> lightsensor.v1.GetCurrentLightSensorRequest
	1, // 1: lightsensor.v1.LightSensorService.GetCurrentLightSensor:output_type -> lightsensor.v1.GetCurrentLightSensorResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lightsensor_v1_lightsensor_proto_init() }
func file_proto_lightsensor_v1_lightsensor_proto_init() {
	if File_proto_lightsensor_v1_lightsensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lightsensor_v1_lightsensor_proto_rawDesc), len(file_proto_lightsensor_v1_lightsensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lightsensor_v1_lightsensor_proto_goTypes,
		DependencyIndexes: file_proto_lightsensor_v1_lightsensor_proto_depIdxs,
		MessageInfos:      file_proto_lightsensor_v1_lightsensor_proto_msgTypes,
	}.Build()
	File_proto_lightsensor_v1_lightsensor_proto = out.File
	file_proto_lightsensor_v1_lightsensor_proto_goTypes = nil
	file_proto_lightsensor_v1_lightsensor_proto_depIdxs = nil
}
