// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/lightsensor/v1/lightsensor.proto

package lightsensorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LightSensorService_GetCurrentLightSensor_FullMethodName = "/lightsensor.v1.LightSensorService/GetCurrentLightSensor"
)

// LightSensorServiceClient is the client API for LightSensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LightSensorServiceClient interface {
	GetCurrentLightSensor(ctx context.Context, in *GetCurrentLightSensorRequest, opts ...grpc.CallOption) (*GetCurrentLightSensorResponse, error)
}

type lightSensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLightSensorServiceClient(cc grpc.ClientConnInterface) LightSensorServiceClient {
	return &lightSensorServiceClient{cc}
}

func (c *lightSensorServiceClient) GetCurrentLightSensor(ctx context.Context, in *GetCurrentLightSensorRequest, opts ...grpc.CallOption) (*GetCurrentLightSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentLightSensorResponse)
	err := c.cc.Invoke(ctx, LightSensorService_GetCurrentLightSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LightSensorServiceServer is the server API for LightSensorService service.
// All implementations must embed UnimplementedLightSensorServiceServer
// for forward compatibility.
type LightSensorServiceServer interface {
	GetCurrentLightSensor(context.Context, *GetCurrentLightSensorRequest) (*GetCurrentLightSensorResponse, error)
	mustEmbedUnimplementedLightSensorServiceServer()
}

// UnimplementedLightSensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLightSensorServiceServer struct{}

func (UnimplementedLightSensorServiceServer) GetCurrentLightSensor(context.Context, *GetCurrentLightSensorRequest) (*GetCurrentLightSensorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentLightSensor not implemented")
}
func (UnimplementedLightSensorServiceServer) mustEmbedUnimplementedLightSensorServiceServer() {}
func (UnimplementedLightSensorServiceServer) testEmbeddedByValue()                            {}

// UnsafeLightSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LightSensorServiceServer will
// result in compilation errors.
type UnsafeLightSensorServiceServer interface {
	mustEmbedUnimplementedLightSensorServiceServer()
}

func RegisterLightSensorServiceServer(s grpc.ServiceRegistrar, srv LightSensorServiceServer) {
	// If the following call panics, it indicates UnimplementedLightSensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LightSensorService_ServiceDesc, srv)
}

func _LightSensorService_GetCurrentLightSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentLightSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightSensorServiceServer).GetCurrentLightSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LightSensorService_GetCurrentLightSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightSensorServiceServer).GetCurrentLightSensor(ctx, req.(*GetCurrentLightSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LightSensorService_ServiceDesc is the grpc.ServiceDesc for LightSensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LightSensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightsensor.v1.LightSensorService",
	HandlerType: (*LightSensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentLightSensor",
			Handler:    _LightSensorService_GetCurrentLightSensor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lightsensor/v1/lightsensor.proto",
}
